### PR TITLE
HPCC-8983 ESP export related changes

### PR DESCRIPTION
**Pull request by afishbeck**
Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by afishbeck** [comment]
@ghalliday here are my initial esphttp and related changes for your review.

**Comment by ghalliday** [comment]
@afishbeck I have included your branch and rebase it onto the latest master.  I've also fixed a few additional issues.

Building on windows (which reveals most of the problems) I have the following problem:

espprotocol.cpp is included in two projects (protocals/http and bindings/SOAP/soaplib) but not really exported from either.  I get link errors from EspDirect and others.

>EclDirectPlugin.obj : error LNK2001: unresolved external symbol "public: virtual class CEspApplicationPort * __thiscall CEspProtocol::queryApplicationPort(int)" (?queryApplicationPort@CEspProtocol@@UAEPAVCEspApplicationPort@@H@Z)

**Comment by afishbeck** [comment]
@ghalliday I can't quite even build master at the moment.  Ming said they haven't done in a while.  I can try to fix whatever issues I'm having and get far enough to link these components.  Any tips on how you manage to build?

**Comment by afishbeck** [comment]
Ming is able to build client tools, but not platform.

**Comment by afishbeck** [comment]
I think turning off cassandra build may help with the biggest block of errors

**Pull request closed without merging**
